adding trivy check

diff --git a/.github/workflows/deploy-infrastructure.yml b/.github/workflows/deploy-infrastructure.yml
--- a/.github/workflows/deploy-infrastructure.yml
+++ b/.github/workflows/deploy-infrastructure.yml
@@ -18,6 +18,16 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
+      - name: Scan for misconfigurations
+        run: |
+          cd terraform 
+          terraform plan --out tfplan.binary
+          terraform show -json tfplan.binary > tfplan.json
+          misconfigs=$(trivy config --severity CRITICAL -f json ./tfplan.json | jq -r '.Results[1].Misconfigurations' | jq length)
+          if [ "misconfigs" -gt 10 ]; then
+            echo "::error::Failing due to many Critical infrastructure misconfigurations: misconfigs"
+            exit 1
+          fi
       - name: Initialise project and view terraform plan
         run: |
           cd terraform 
