being able to specify image to deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,6 +37,15 @@ jobs:
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a
 
+      - name: Validate Container Vulnerabilities
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+        run: |
+          highCVE=$(aws ecr describe-image-scan-findings --repository-name takehome/tasky --image-id imageTag=1bca93a901d144090f3a2deac8f32101262fe4e9 | jq -r '.imageScanFindings.findingSeverityCounts.HIGH') 
+          if [ "$highCVE" -gt 10 ]; then
+                      echo "::error::Failing due to many High vulnerabilities: $highCVE"
+                      exit 1
+          fi
       - name: Deploy to EKS
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
